### PR TITLE
Update keypad_willox.lua

### PR DESCRIPTION
**Pull request by slaVACo**
fixed spam error

### CODE REVIEW

**Comment by slaVACo** [comment]
If gmod_tool 'Keypad' to use the usual props that will be this error.

[ERROR] addons/keypad/lua/weapons/gmod_tool/stools/keypad_willox.lua:85: attempt to call method 'GetKeypadOwner' (a nil value)
  1. RightClick - addons/keypad/lua/weapons/gmod_tool/stools/keypad_willox.lua:85
   2. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:250

**Comment by willox** [comment]
It would be better to fix line 71

**Comment by Jophes** [comment]
Is it possible this is related to #20 ? Where somehow an entity of type keypad, doesn't have a function that it should have?

**Comment by slaVACo** [comment]
> It would be better to fix line 71

Well or so

**Comment by willox** [comment]
> Is it possible this is related to #20 ? Where somehow an entity of type keypad, doesn't have a function that it should have?

i don't think so. i have no idea what could cause the other issue

**Comment by willox** [comment]
did i not push this to steam?

**Comment by slaVACo** [comment]
Idk

ср, 28 июл. 2021 г., 21:42 William Wallace ***@***.***>:

**Pull request merged**
